### ISSUE TITLE
How i get only the content of a gist.

### ISSUE THREAD

**Issue by plopez01** [jonschlinkert/gists#8]
I don't know how to get only the content. Is the json parsed? I tried to parse but i get error. If i try to acces an specific i get undefined.

``res.files.text.txt.content`` if i use this i get error @jonschlinkert

**Comment by doowb** [comment]
@plopez01 I didn't notice the last line at first and I was going to point you to the api documentation here: https://developer.github.com/v3/gists/#get-a-single-gist

It looks like you started to figure it out, but one thing that you need to do is use square brackets and quote the file name like this: `res.files['text.txt'].content`

This is because of the `.` in the file name before the extension.

I hope this helps.
